
server:
  port: 8081

spring:
  rabbitmq:
    username: admin
    password: nimda
    listener:
      simple:
        retry:
          enabled: 'true'
          max-attempts: '3'
          initial-interval: 10s
        acknowledge-mode: 'auto'
